spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    generate-unique-name : false

mybatis:
  mapper-locations: /mapper/*.xml
  type-aliases-package: me.gracenam.musicsampleapi
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:log4j2.yml